site_url: "https://ai-tlc.github.io"

backend:
  name: github
  repo: ai-tlc/ai-tlc.github.io
  branch: main
  base_url: https://decap-oauth-proxy.ai-tlc.workers.dev

local_backend: true

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

publish_mode: editorial_workflow

collections:
  - name: "docs_en"
    label: "Docs (English)"
    folder: "docs"
    create: false
    format: "frontmatter"
    extension: "md"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Sidebar Label", name: "sidebar_label", widget: "string", required: false }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "docs_nl"
    label: "Docs (Nederlands)"
    folder: "i18n/nl/docusaurus-plugin-content-docs/current"
    create: false
    format: "frontmatter"
    extension: "md"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Sidebar Label", name: "sidebar_label", widget: "string", required: false }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
